package miniplc0java.instruction;

public enum Operation {
    NOP,PUSH,POP,POPN,DUP,LOCA,ARGA,GLOBA,LOAD8,LOAD16,
    LOAD32,LOAD64,STORE8,STORE16,STORE32,STORE64,ALLOC,
    FREE,STACKALLOC,ADDI,SUBI,MULI,DIVI,ADDF,SUBF,MULF,
    DIVF,DIVU,SHR,AND,OR,XOR,NOT,CMPI,CMPF,CMPU,NEGI,
    NEGF,ITOF,FTOI,SHRL,SETLT,SETGT,BR,BRFALSE,BRTRUE,
    CALL,RET,CALLNAME,SCANI,SCANF,PRINTI,PRINTC,PRINTF,
    PRINTS,PRINTLN,PANIC
}